### ISSUE TITLE
Form手动验证，能否添加

### ISSUE THREAD

**Issue by lx11573** [NG-NEST/ng-nest#210]

**Comment by ng-nest-moon** [comment]
@lx11573  Form 手动验证指的是与 Input 提供的正则验证类似？可以在 Control 配置中提供一个 vaild 函数属性

**Comment by lx11573** [comment]
> @lx11573 Form 手动验证指的是与 Input 提供的正则验证类似？可以在 Control 配置中提供一个 vaild 函数属性

根据官方示例使用Form时，一进入页面就已经进行了表单验证，并且展示了错误提示语。
我所指的意思是，可否进入页面时，不进行验证，等到需要提交数据时再去发起验证

**Comment by ng-nest-moon** [comment]
> > @lx11573 Form 手动验证指的是与 Input 提供的正则验证类似？可以在 Control 配置中提供一个 vaild 函数属性
> 
> 根据官方示例使用Form时，一进入页面就已经进行了表单验证，并且展示了错误提示语。 我所指的意思是，可否进入页面时，不进行验证，等到需要提交数据时再去发起验证

可以，我修改一下，下个版本加上去
