### ISSUE TITLE
XIconModule Bug: 覆写了HttpClientModule以及HttpInterceptors 

### ISSUE THREAD

**Issue by HouSuYuan** [NG-NEST/ng-nest#215]
## 哪些组件包含错误？

`XIconModule`、`XInputModule`,、`XButtonModule`... 凡是引用`XIconModule`的模块。

## 描述
在项目中使用`XInputModule`, `XButtonModule`, `XIconModule` 导致根应用`HttpInterceptor`被`XIconModule`覆盖。

## 原因
在`XIconModule`中导入了`HttpClientModule`。

https://angular.cn/api/common/http/HttpInterceptor#usage-notes
>**HttpInterceptor 使用说明**
>
>要想在整个应用中使用 HttpInterceptors 的同一个实例，就只能在 AppModule 模块中导入 HttpClientModule，并且把拦截器都添加到应用的根注入器中。 如果你在不同的模块中多次导入 HttpClientModule，则每次导入都会创建 HttpClientModule 的一个新复本，它将会覆盖根模块上提供的那些拦截器。

https://github.com/NG-NEST/ng-nest/blob/master/lib/ng-nest/ui/icon/icon.module.ts

``` ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { XIconComponent } from './icon.component';
import { HttpClientModule } from '@angular/common/http';
import { XIconService } from './icon.service';
import { XIconProperty } from './icon.property';

@NgModule({
  declarations: [XIconComponent, XIconProperty],
  exports: [XIconComponent],
  imports: [CommonModule, HttpClientModule],
  providers: [XIconService]
})
export class XIconModule {}
```

**Comment by ng-nest-moon** [comment]
已经解决 https://github.com/NG-NEST/ng-nest/commit/c3a9f5da6e2bc99ec178c73e5ea537470c53aadf
